"""``marketlens-mcp add-capability`` (contract 9.4): write the skeleton of a
new tool, its golden test, fixture and golden file, refusing to overwrite.

In a marketlens-mcp checkout (``src/marketlens_mcp/`` under the current
directory) it writes under ``providers/alpaca/tools/`` (``--provider alpaca``)
or ``analytics/tools/`` (``--provider local``); elsewhere it needs
``--package PKG --root DIR`` and writes a plugin's ``tools/`` module.
"""

from __future__ import annotations

import json
import pathlib
import re

from marketlens_schema import BUILTIN_MODELS, QUERY_ROW_SCHEMA_NAME

from .plugin_api import CAPABILITY_ID_RE, TOOL_NAME_MAX, TOOL_NAME_RE

ALPACA_ENV = ("ALPACA_API_KEY", "ALPACA_SECRET_KEY")
SPECS_DIR = pathlib.Path("src/marketlens_mcp/providers/alpaca/specs")


class ScaffoldError(Exception):
    pass


def _camel(name: str) -> str:
    return "".join(part.capitalize() for part in name.split("_"))


def _find_operation(root: pathlib.Path, operation: str) -> str:
    specs = sorted((root / SPECS_DIR).glob("*.json"))
    for path in specs:
        try:
            doc = json.loads(path.read_text(encoding="utf-8"))
        except (OSError, ValueError):
            continue
        for route, methods in (doc.get("paths") or {}).items():
            for method, op in (methods or {}).items():
                if isinstance(op, dict) and op.get("operationId") == operation:
                    if method.lower() != "get":
                        raise ScaffoldError(
                            f"operation {operation} is {method.upper()} {route}; v1 maps GET only (record it in "
                            "EXCLUDED_OPERATIONS as a write instead)"
                        )
                    return f"GET {route}"
    raise ScaffoldError(f"operation {operation} not found in the pinned specs under {SPECS_DIR}")


def _tool_module(
    *,
    name: str,
    capability: str,
    provider: str,
    route: str,
    operation: str | None,
    model: str | None,
    golden: str,
    builtin_checkout: bool,
) -> str:
    camel = _camel(name)
    imports = ["from marketlens_mcp.plugin_api import ToolContext, ToolError, ToolOutput, ToolSpec"]
    if model and builtin_checkout:
        cls = BUILTIN_MODELS[model]
        imports.append(f"from {cls.__module__} import {cls.__name__}")
        output = cls.__name__
    elif model:
        output = repr(model)
    else:
        output = repr(QUERY_ROW_SCHEMA_NAME)
    env = ALPACA_ENV if provider == "alpaca" else ()
    upstream = f"({operation!r},)" if operation else "()"
    return f'''"""{name}: TODO one line on what it returns. Generated by marketlens-mcp add-capability."""

from __future__ import annotations

from pydantic import BaseModel, ConfigDict

{chr(10).join(imports)}


class {camel}Args(BaseModel):
    model_config = ConfigDict(extra="forbid")

    # TODO: the parameters, each with Field(..., description=...).


async def {name}(ctx: ToolContext, args: {camel}Args) -> ToolOutput:
    raise ToolError("not_implemented", "{name} is not implemented yet.")


SPECS = (
    ToolSpec(
        name="{name}",
        capability="{capability}",
        title="{name.replace("_", " ").capitalize()}",
        description="TODO: what the model reads: purpose, key parameters, units; large results are stored "
        "and you get a result_id.",
        readme="TODO: one line for the README table",
        input_model={camel}Args,
        # TODO: the canonical model (class) this tool returns, registered by its provider or plugin.
        output_model={output},
        provider="{provider}",
        route="{route}",
        handler={name},
        golden_test="{golden}",
        upstream_operations={upstream},
        parity_names=(),
        env={env!r},
        output_risk="api_structured",
    ),
)
'''


def _test_module(name: str) -> str:
    return f'''"""Golden test for {name} (generated by marketlens-mcp add-capability)."""

from __future__ import annotations

import json
import pathlib

import pytest

HERE = pathlib.Path(__file__).parent
FIXTURE = HERE / "fixtures" / "{name}.json"
GOLDEN = HERE / "golden" / "{name}.json"


@pytest.mark.skip(reason="{name}: fill the fixture and the golden file, then remove this skip")
def test_{name}_golden():
    raw = json.loads(FIXTURE.read_text(encoding="utf-8"))
    expected = json.loads(GOLDEN.read_text(encoding="utf-8"))
    # Run {name} on `raw` (an httpx.MockTransport serving it) with
    # marketlens_mcp.testing.call_tool and compare rows, absent, pagination and
    # provenance (minus fetched_at) with `expected`; assert the absence rule:
    # marketlens_schema.unexplained_absences(rows, absent) == [].
    assert raw and expected
'''


def add_capability(
    name: str,
    *,
    capability: str,
    provider: str,
    operation: str | None = None,
    model: str | None = None,
    package: str | None = None,
    root: str | pathlib.Path | None = None,
    cwd: pathlib.Path | None = None,
) -> list[pathlib.Path]:
    """Write the skeleton; return the written paths (relative to the target
    root). Raises ScaffoldError with a readable reason."""
    here = pathlib.Path.cwd() if cwd is None else cwd
    if not TOOL_NAME_RE.match(name):
        raise ScaffoldError(
            f"tool name {name!r} must be snake_case ASCII starting with a letter, e.g. market_auctions"
        )
    if len(name) > TOOL_NAME_MAX:
        raise ScaffoldError(f"tool name {name!r} must be at most {TOOL_NAME_MAX} characters")
    if not CAPABILITY_ID_RE.match(capability):
        raise ScaffoldError(f"capability id {capability!r} is not valid (e.g. market or myplugin.extra)")
    if provider not in ("alpaca", "local"):
        raise ScaffoldError("--provider must be alpaca or local")
    if operation and provider != "alpaca":
        raise ScaffoldError("--operation names an upstream operation and needs --provider alpaca")
    if (package is None) != (root is None):
        raise ScaffoldError("--package and --root go together (a plugin's import package and its folder)")

    if package is not None:
        if not re.fullmatch(r"[A-Za-z_][A-Za-z0-9_]*", package):
            raise ScaffoldError(f"--package {package!r} is not an importable package name")
        base = pathlib.Path(root).expanduser()
        if not base.is_absolute():
            base = here / base
        tool_rel = pathlib.Path("src") / package / "tools" / f"{name}.py"
        tests_rel = pathlib.Path("tests")
        builtin = False
    else:
        if not (here / "src" / "marketlens_mcp").is_dir():
            raise ScaffoldError(
                "run this in a marketlens-mcp checkout (src/marketlens_mcp/ under the current folder), or pass "
                "--package PKG --root DIR to scaffold a plugin's tool"
            )
        base = here
        sub = "providers/alpaca/tools" if provider == "alpaca" else "analytics/tools"
        tool_rel = pathlib.Path("src/marketlens_mcp") / sub / f"{name}.py"
        tests_rel = pathlib.Path("tests") / ("alpaca" if provider == "alpaca" else "analytics")
        builtin = True
        if model and model not in BUILTIN_MODELS:
            raise ScaffoldError(
                f"unknown model {model!r}; built-in models: {', '.join(sorted(BUILTIN_MODELS))}"
            )

    if operation:
        route = _find_operation(base, operation)
    else:
        route = "GET TODO" if provider == "alpaca" else f"duckdb:{name}"
    golden = (tests_rel / f"test_{name}.py").as_posix()
    files = {
        tool_rel: _tool_module(
            name=name,
            capability=capability,
            provider=provider,
            route=route,
            operation=operation,
            model=model,
            golden=golden,
            builtin_checkout=builtin,
        ),
        tests_rel / f"test_{name}.py": _test_module(name),
        tests_rel / "fixtures" / f"{name}.json": json.dumps({"_synthetic": True}) + "\n",
        tests_rel / "golden" / f"{name}.json": "{}\n",
    }
    for rel in files:
        if (base / rel).exists():
            raise ScaffoldError(f"{rel.as_posix()} already exists; the scaffold never overwrites")
    for rel, text in files.items():
        target = base / rel
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(text, encoding="utf-8")
    return list(files)


def next_steps(name: str, provider: str, package: str | None) -> str:
    if package is not None:
        init = f"src/{package}/tools/__init__.py"
    else:
        init = (
            "src/marketlens_mcp/"
            + ("providers/alpaca" if provider == "alpaca" else "analytics")
            + "/tools/__init__.py"
        )
    return (
        f"Add '{name}' to MODULES in {init}, implement the handler, fill the fixture and golden file, then run "
        "make test and make readme."
    )
